############
# Settinga #
############

# scrollback_lines 1000
cursor_shape_unfocused underline
shell_integration no-cursor

######
# UI #
######

include ~/.config/kitty/source/ui.conf

#########
# Trail #
#########

# include /home/rascal/.dotfiles/config/kitty/source/trail.conf
# cursor_trail 200
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2

############
# Bindings #
############

map ctrl+shift+left  send_text all \x1b[1;6D
map ctrl+shift+right send_text all \x1b[1;6C

allow_remote_control yes


# Aktifkan border antar split
# draw_minimal_borders no

# map ctrl+shift+left  resize_window narrower 5
# map ctrl+shift+right resize_window wider 5
# map ctrl+shift+up    resize_window taller 5
# map ctrl+shift+down  resize_window shorter 5
