[config]

[templates.test]
input_path      = "~/.config/matugen/templates/test.conf"
output_path     = "~/.config/matugen/generated.bak/test.conf"
post_hook       = "echo Success"

[templates.alacritty]
input_path      = "~/.config/matugen/templates/general/alacritty.toml"
output_path     = "~/.myenv/theme/generated/live.bak/alacritty/theme.toml"
post_hook       = "mkdir -p ~/.myenv/theme/generated/live.bak/alacritty"

[templates.kitty]
input_path      = "~/.config/matugen/templates/general/kitty.conf"
output_path     = "~/.myenv/theme/generated/live.bak/kitty/theme.conf"
post_hook       = "pkill -SIGUSR1 kitty"

[templates.lazygit]
input_path      = "~/.config/matugen/templates/general/lazygit.yml"
output_path     = "~/.myenv/theme/generated/live.bak/lazygit/config.yml"

[templates.css]
input_path      = "~/.config/matugen/templates/general/source.css"
output_path     = "~/.myenv/theme/generated/live.bak/css/theme.css"
post_hook       = """
    dconf write /org/gnome/desktop/interface/gtk-theme "'Adwaita'"
    dconf write /org/gnome/desktop/interface/gtk-theme "'Kanagawa-Dark-Dragon'"
"""

[templates.scss]
input_path      = "~/.config/matugen/templates/general/source.scss"
output_path     = "~/.myenv/theme/generated/live.bak/scss/_theme.scss"

[templates.rasi]
input_path      = "~/.config/matugen/templates/general/source.rasi"
output_path     = "~/.myenv/theme/generated/live.bak/rasi/theme.rasi"

[templates.nvim]
input_path      = "~/.config/matugen/templates/general/nvim.lua"
output_path     = "~/.myenv/theme/current/nvim/theme.lua"

[templates.herdr]
input_path      = "~/.config/matugen/templates/general/herdr.toml"
output_path     = "~/.myenv/theme/generated/live.bak/herdr/config.toml"
post_hook       = "herdr server reload-config"
