# Generals
$gapsIn = 1
$gapsOut = 5
$borderSize = 2
$colActiveBorder2 = rgba(978BF8ee)
$colActiveBorder1 = rgba(C299FFee)
$colActiveBorderDeg = 45deg
$colInactiveBorder = rgba(0E0C13ff)

# Decorations
$blur = true
$blurSize = 4
$blurPasses = 3
$rounding = 7
$shadow = true
$shadowRange = 6
$shadowRenderPower = 1
$shadowColor = rgba(7, 0, 9, 0.88)

$footOpacity = 0.85

